############################
#   Makefile Hello world   #
############################

# Este es el makefile mas facil que podemos llegar a hacer, solo tenemos una
# única dependencia, helloworld.c, es tan simple de hecho, que ni siquiera
# tenemos que separar el proceso entre el compiler y el linker

main: helloworld.c
	gcc helloworld.c -o helloworld